### ISSUE TITLE
MVPリリースレビュー

### ISSUE THREAD

**Issue by shurijoc** [gussan-is-glassheart/free_theme#75]
提出ありがとうございます！

就活を踏まえて、以下の観点からレビューさせていただきますね。

```markdown
💡 就活レビュー観点

1. 課題に対してサービス内で適切な解決策となる機能を提供できているか
2. 就活において十分な技術力を示せる機能を実装しているか
3. UIでユーザーが迷わないような導線を作れているか・ユーザーが使いたくなるようなサービス設計ができているか
```

### 1に関して

サービスを開発する上で「課題に対して、適切な仮説を立てて、その仮説に対して妥当な解決方法を機能として実装しているか」というところが大事になります。

このissueのコメントに、ユーザーが抱える問題に対して仮説を立てて、今実装している機能を解決方法として当てていただけますか？
「旅行で暇→ミッション形式の写真撮影で解決」は方向性は良いのですが少しギャップがあるかなと思い、就活でも突っ込まれそうかなと思いまして。

例えば下記のようなフォーマットです。

**課題1**

旅行中に、ふとした時間が暇になってグダってしまうことがある

**問題点仮説**

- ?????

**仮説に対する解決策**

- 旅行と相性の良い写真撮影というテーマでミッション形式でやることをユーザーに与える

のような形です！

この課題・仮説・解決策を書いた上で機能を見直してみてください。

### 2に関して

```markdown
💡 技術的なところでいうと以下のような箇所がポイントです。

- 基本的なRailsのCRUDを使っている
- CRUDにプラスαで独自のロジックを使用している
  - 例: ActionCableやHotwireなどRailsの技術を使用している
```

今回でいうと基本的なRails CRUD + APIで構成されているのでプラスアルファの技術アピールポイントが必要かと思います。
例えば以下のような機能などがあります！

- 画像合成
  - お題で撮った写真と文字（テーマとか・旅行名とか）を合成してTwitterにシェアできる機能
- Rails ActionCableでWebSocket実装
  - 今ミッションに挑戦してる人の人数や、挑戦内容がリアルタイムでわかる機能

あとは切り口としては、以下のように技術ドリブンで機能追加する方法もありますので、どういったことができるのか参照してみてください！

```
- RailsのHotwireを使う
- RailsのActionCableを使う
```

### 3に関して

UIとユーザビリティに関しては、以下の点が気になりました。

```
1. TOPの文言から何を解決するサービスなのかピンと来づらい（上記仮説などを追記するとわかりやすくなると思います。）
2. 新規登録後一覧からミッションに参加できず、毎回ヘッダーから遷移しないといけない
```

まずは土台となる1に関して再度ご確認をお願いします。
それ以外の追加機能などは1が決まってから再度決めましょう！

以上がレビューとなります、ご確認お願いいたします！

P.S

日々レビュー内容も改善しているため、もともとのポートフォリオボードとは、若干異なる観点のレビュー箇所があります、申し訳ございません！

**Comment by gussan-is-glassheart** [comment]
お返事遅くなり申し訳ございません！
レビューありがとうございます！

ご指摘いただきました箇所について、仮説と解決策を記述しました。
READMEの内容と重複してしまっている箇所かもしれませんが、現在機能として設けている「撮影」というお題(機能)にフォーカスを当てた仮説と解決策で考えてみたので、ご確認をいただけますと幸いです！

---

**課題**
旅行やお出かけでメインの目的(観光)を終えたが、時間が余ってしまい次の目的がない。または次の目的(食事や帰宅など)にはまだ時間が早く、時間を無駄にしてしまうことがある。

**問題点仮説**
- 検索で色々な観光地やおすすめスポットなどはあるけれども、どこにするか迷ってしまう。
- 外出しているのにスマホゲームやSNSなど、普段家でもできることで時間を潰してしまっている。

**仮説に対する解決策**
- 撮影のミッション形式で出題することで、迷っている行き先を被写体がある目的地に指定する(決める)ことができる。
- 撮影のお題を出題することで、被写体を探すという、外出先での町並みを散策する機会ができる。

**Comment by shurijoc** [comment]
@gussan-is-glassheart 

ありがとうございます！

> 検索で色々な観光地やおすすめスポットなどはあるけれども、どこにするか迷ってしまう。

こちらの仮説の部分をもう一段回分割していただけますか？
なぜ迷ってしまうのか→探すのが面倒、そもそもそこまで行く場所もない（時間も微妙に足りない）などです！

> 外出しているのにスマホゲームやSNSなど、普段家でもできることで時間を潰してしまっている。

こちらに関しては、最終的には１つ目の仮説に帰結しそうで、そもそも問題点の方で例として書けるかなと思います！

なぜ普段家でできることをしてしまうのか→探した結果あまり興味がそそられるものがなかった、迷った結果選ぶのをあきらめた（上記仮説に繋がる）ということかなと思いまして。

確認をお願いします！

**Comment by gussan-is-glassheart** [comment]
お返事が遅くなり申し訳ございません！
ご指摘いただきました通り、仮説2は仮説1に帰結できる内容となっておりましたので、仮説を集約しました。
合わせて解決策も集約した仮説に対する解決策になるよう、調整しております。

**問題点仮説**
- 近くの観光地を検索するも近いところに興味がそそられるもの(手頃な観光地)がなく、調べていくうちにダレてしまい、普段家でもできるスマホゲームやSNSをしてしまう。

仮説については小沼さんのご指摘にあった「興味をそそられるものがなかった」という要因が大きいように思います。
課題で記載してある「メインの目的を終えた」状況というのは、お手頃な観光スポットを探すケースが多いように思います(自分の場合はの話になりますが)。
なので、すこし抽象的な言い方にはなりますが、移動距離などを含めた「イイ感じ」のものがなかなか見つからないため、ダレてしまったことで、ついつい普段簡単に時間を潰せるツールを触ってしまう。という流れになると考えます。

**仮説に対する解決策**
- ミッション形式で出題することで、「この観光スポットならお題の撮影ができるかも？」という考えで調べることができるため、行き先の選択肢(きっかけ)を増やすことができる。
- お題によっては気軽に撮影できるものもあるため、近くを散策するという選択肢を増やすことができる。

解決策については、先述した仮説をもとに、「イイ感じ」の観光スポットが見当たらない場合でも、出題されたお題を理由に目的地を決定する要因(判断材料)になれば、と思っております。
また2つ目の解決策にあるように、簡単な被写体の撮影のお題もあるため、「あえて近場の散策をしてみる」という選択肢もできると考えております。

**Comment by shurijoc** [comment]
@gussan-is-glassheart 

レビュー観点の1に関して、とてもスッキリして良いと思います！

次に2に関して、下記どちらかを本リリースまでに実装してみてはいかがでしょうか？もちろん他の「自分が欲しい機能」でも何かしらの技術を使っているのでそちらでも問題ございません！

- 画像合成
    - お題で撮った写真と文字（テーマとか・旅行名とか）を合成してTwitterにシェアできる機能
- Rails ActionCableでWebSocket実装
    - 今ミッションに挑戦してる人の人数や、挑戦内容がリアルタイムでわかる機能

**Comment by gussan-is-glassheart** [comment]
お返事ありがとうございます！
本リリースまでの機能実装について、画像合成のことでお伺いさせていただきたいです。

- 「お題で撮った写真と文字を合成」とは、お題を達成した画像に任意で装飾ができる画像加工機能のようなイメージでしょうか？もしくは装飾はあくまで固定にして、ユーザーに装飾するか否かを選択してもらうようなイメージでしょうか？
	- あくまでアドバイスとして言っていただいたかとは思いますが、画像合成の認識について自分のイメージと合っているのかわからず、参考のようなイメージがあれば教えていただけますと幸いです。
- Twitterのシェア機能は、(加工した)画像データを保持したままTwitterにシェアできるようなイメージでしょうか？
	- Twitterへのシェア機能は過去に実装を試みたのですが、その時に調べたところ、画像を保持した状態でTwitterにシェアすることはできない(できたとしても、一度画像をTwitterにアップして、そのURLをTwitterの投稿に記載するという方法で、現在の運用方法にはそぐわないのではないか)と判断しました。
	  もしTwitterに画像をシェアする場合、下記の方法しか無いでしょうか？

		 - (1) 加工した画像を一度ユーザーのほうでダウンロード
	 	- (2) Twitterシェアボタンで投稿画面を起動
	 	- (3) 投稿画面から手動でダウンロードした画像をセットしてもらいTwitterに投稿

テクニカル的な質問で恐縮ではございますが、画像のシェア機能は本サービスにはぜひあったほうが良い機能と考えておりますので、教えていただけますと幸いです。
もしここ(Git hubでのコメント)で質問するべき内容ではない場合、改めてコミュニティに投稿させていただきます！

**Comment by shurijoc** [comment]
> もしくは装飾はあくまで固定にして、ユーザーに装飾するか否かを選択してもらうようなイメージでしょうか

こちらのイメージですね！例えばこういった方法があります。
https://tech.mof-mof.co.jp/blog/rails-minimagick-image-composition/

> Twitterのシェア機能

こちらについてはTwitterカードを使うようにmetaタグを設定すれば実装できます。大まかには下記のようなイメージです。

https://unique1.co.jp/column/sns_operation/3033/

1. ユーザーの写真投稿時にお題と文字の画像合成をしてcareerwaveなどでs3へアップロードする
2. アップロードしたファイルのURLを写真投稿詳細のmeta tagへ設定する
3. TwitterのURLシェア時にそのURLのOGPが表示される

**Comment by gussan-is-glassheart** [comment]
お返事とイメージの共有ありがとうございます！
参考URLをもとに機能の実装を進めさせていただきます！

**Comment by gussan-is-glassheart** [comment]
画像加工機能およびTwitterカードについて、機能を実装しましたので、ご確認をお願いいたします！

**□画像加工**
画像投稿時、画像にテーマタイトルを埋め込むかのチェックボックスを設けて、ユーザーが任意で選べるように設定しました。

**□Twitterカード**
テーマ達成ページでTwitterへのシェアボタンを設置しました。シェアボタンを押下するとお題を達成した画像がTwitterカードに表示されるようにしております。

機能に関する説明は以上になります。
他機能追加にあたり気になることがありましたので、幾つか質問させてください。

- テーマ達成ページのアクセス権限について
	- これまでテーマ達成ページには、未ログインユーザーおよびテーマを発行したユーザーでない場合はリダイレクトをされるように設定しておりました。Twitterカードで達成した画像を表示させるためには、(クローラーがmetaタグを読むために)どうしてもテーマ達成ページにアクセス権限を解除する必要があり、ThemeBoardsのshowのみ表示されるように権限を変更しております。もしこの方法が運用上良くないなどありましたら、ご指摘をいただけますとありがたいです。
- Twitterカードに任意の画像が表示されるまでのラグについて
	- テーマ詳細画面のURLを共有すると、お題を達成した画像がTwitterカードに表示されるように設定しておりますが、画像が表示されるまでに最大2日程度のラグがあるように感じます。
	  これはTwitterの仕様上、仕方のないことなのでしょうか？なおOGP確認ツールでは問題なく表示され、TwitterのCard validatorでも特にエラーは確認できませんでした。

もし何かお気づきのことなどありましたら、教えていただけると大変助かります。

**Comment by shurijoc** [comment]
実装ありがとうございます！良いですね！

> テーマ達成ページのアクセス権限について

まったく問題ないと思います！

>Twitterカードに任意の画像が表示されるまでのラグについて

もう少し短かった気がするんですが、Twitter側のキャッシュの仕様次第なので一旦はしょうがないかと思います。

内容良いと思いますのでLGTMです！

![nise_rantekun](https://github.com/gussan-is-glassheart/free_theme/assets/6407534/8a69137b-d766-462a-91b4-7bf8b27cf9c0)

**Comment by gussan-is-glassheart** [comment]
ありがとうございます！
レビュー3でいただいていたトップの文言変更と、一覧ページでの新規テーマ作成ボタンを設置しました！
これにて本issuesをcloseにさせていただきます。
MVPレビューと追加機能のアドバイスありがとうございました🙇
